Add extra documentation

diff --git a/.github/workflows/build-deploy-version.yml b/.github/workflows/build-deploy-version.yml
--- a/.github/workflows/build-deploy-version.yml
+++ b/.github/workflows/build-deploy-version.yml
@@ -7,6 +7,10 @@ on:
         description: 'Outcome if user manually confirmed the start of the deploy script'
         type: string
         required: true
+      environment:
+        description: 'The environment to build and deploy to'
+        required: true
+        type: string
       target_version:
         description: 'The version of that needs to be deployed'
         required: true
@@ -77,10 +81,21 @@ jobs:
             exit 1
           fi
           echo "status=success" >> $GITHUB_OUTPUT
-
+  check-environment:
+    name: Check if proper environment is passed
+    runs-on: ubuntu-latest
+    steps:
+      - name: Only allow staging and production
+        run: |
+          if [[ "${{ inputs.environment }}" == "staging" || "${{ inputs.environment }}" == "production" ]]; then
+          echo "Running workflow with environment: ${{ inputs.environment }}."
+          else
+          echo "Invalid environment. Only 'staging' or 'production' are allowed."
+          exit 1
+          fi
   determine-ecr-image-name:
     name: Determine ecr image name based on environment
-    needs: ensure-master-branch
+    needs: [check-environment, ensure-master-branch]
     outputs:
       image_name: ${{ steps.image_name.outputs.image_name }}
     runs-on: ubuntu-latest
@@ -91,6 +106,14 @@ jobs:
           repository: rentmanpublic/actions
           token: ${{ secrets.GITHUB_TOKEN }}
           path: actions
+          ref: feature/multi-region-deploy
+      - name: Checkout to release repo
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ github.repository }}
+          token: ${{ steps.github-token.outputs.token || secrets.GITHUB_TOKEN }}
+          path: target_repository_folder
+          ref: master
       - id: image_name
         name: Check which image name to use based on enviroment
         run: |
@@ -105,7 +128,7 @@ jobs:
     needs: determine-ecr-image-name
     if: needs.ensure-master-branch.outputs.status == 'success'
     with:
-      image_name: ${{ needs.determine-image-name.outputs.image_name }}
+      image_name: ${{ needs.determine-ecr-image-name.outputs.image_name }}
       image_tag: latest ${{ inputs.target_version  }}
       version: ${{ inputs.target_version }}
       dockerfile: ${{ inputs.dockerfile }}
@@ -127,7 +150,7 @@ jobs:
   deploy:
     name: Deploy to ECS
     needs: docker-build
-    uses: rentmanpublic/actions/.github/workflows/ecs-redeploy-service.yml@master
+    uses: rentmanpublic/actions/.github/workflows/ecs-redeploy-service.yml@feature/multi-region-deploy
     with:
       environment: ${{ inputs.environment }}
     secrets:
diff --git a/.github/workflows/build-release-branch.yml b/.github/workflows/build-release-branch.yml
--- a/.github/workflows/build-release-branch.yml
+++ b/.github/workflows/build-release-branch.yml
@@ -7,6 +7,10 @@ on:
         description: 'Outcome if user manually confirmed the start of the deploy script'
         type: string
         required: true
+      environment:
+        description: 'The environment to build and deploy to'
+        required: true
+        type: string
       version_file_path:
         description: The path to the php version file
         type: string
@@ -60,6 +64,18 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
+  check-environment:
+    name: Check if proper environment is passed
+    runs-on: ubuntu-latest
+    steps:
+      - name: Only allow staging and production
+        run: |
+          if [[ "${{ inputs.environment }}" == "staging" || "${{ inputs.environment }}" == "production" ]]; then
+          echo "Running workflow with environment: ${{ inputs.environment }}."
+          else
+          echo "Invalid environment. Only 'staging' or 'production' are allowed."
+          exit 1
+          fi
   ensure-correct-branch:
     name: Check current branch
     if: ${{ inputs.deploy_confirmation == 'DEPLOY' || inputs.deploy_confirmation == 'YOLO' }}
@@ -75,7 +91,7 @@ jobs:
 
   determine-ecr-image-name:
     name: Determine ecr image name based on environment
-    needs: ensure-correct-branch
+    needs: [check-environment, ensure-correct-branch]
     outputs:
       image_name: ${{ steps.image_name.outputs.image_name }}
     runs-on: ubuntu-latest
@@ -86,6 +102,14 @@ jobs:
           repository: rentmanpublic/actions
           token: ${{ secrets.GITHUB_TOKEN }}
           path: actions
+          ref: feature/multi-region-deploy
+      - name: Checkout to release repo
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ github.repository }}
+          token: ${{ steps.github-token.outputs.token || secrets.GITHUB_TOKEN }}
+          path: target_repository_folder
+          ref: master
       - name: Check which image name to use based on enviroment
         id: image_name
         run: |
@@ -107,7 +131,7 @@ jobs:
           repository: rentmanpublic/actions
           token: ${{ secrets.GITHUB_TOKEN }}
           path: actions
-          ref: master
+          ref: feature/multi-region-deploy
       - name: Fetch most current tag
         id: tag_version
         uses: mathieudutour/github-tag-action@v6.2
@@ -121,7 +145,7 @@ jobs:
     needs: [determine-ecr-image-name, determine-version] # force it to wait on previous steps
     uses: rentmanpublic/actions/.github/workflows/ecr-build-and-push.yml@master
     with:
-      image_name: ${{ needs.determine-image-name.outputs.image_name }}
+      image_name: ${{ needs.determine-ecr-image-name.outputs.image_name }}
       image_tag: latest
       dockerfile: ${{ inputs.dockerfile }}
       platforms: amd64
@@ -142,7 +166,7 @@ jobs:
   deploy:
     name: Deploy to ECS
     needs: docker-build
-    uses: rentmanpublic/actions/.github/workflows/ecs-redeploy-service.yml@master
+    uses: rentmanpublic/actions/.github/workflows/ecs-redeploy-service.yml@feature/multi-region-deploy
     with:
       environment: ${{ inputs.environment }}
     secrets:
diff --git a/.github/workflows/redeploy-latest.yml b/.github/workflows/redeploy-latest.yml
--- a/.github/workflows/redeploy-latest.yml
+++ b/.github/workflows/redeploy-latest.yml
@@ -11,7 +11,6 @@ on:
         description: 'The environment to build and deploy to'
         required: true
         type: string
-        default: 'staging'
     secrets:
       AWS_ACCESS_KEY_ID:
         required: true
@@ -25,8 +24,21 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
+  check-environment:
+    name: Check if proper environment is passed
+    runs-on: ubuntu-latest
+    steps:
+      - name: Only allow staging and production
+        run: |
+          if [[ "${{ inputs.environment }}" == "staging" || "${{ inputs.environment }}" == "production" ]]; then
+          echo "Running workflow with environment: ${{ inputs.environment }}."
+          else
+          echo "Invalid environment. Only 'staging' or 'production' are allowed."
+          exit 1
+          fi
   deploy:
     name: Redeploy latest image available on ECR to ECS
+    needs: check-environment
     if: ${{ inputs.deploy_confirmation == 'DEPLOY' || inputs.deploy_confirmation == 'YOLO' }}
     uses: rentmanpublic/actions/.github/workflows/ecs-redeploy-service.yml@feature/multi-region-deploy
     with:
