Initial setup of redeploy script for multiple regions

diff --git a/.github/workflows/build-tag-release-master.yml b/.github/workflows/build-tag-release-master.yml
--- a/.github/workflows/build-tag-release-master.yml
+++ b/.github/workflows/build-tag-release-master.yml
@@ -3,17 +3,18 @@ name: Build, Tag and Release Master
 on:
   workflow_call:
     inputs:
-      name:
-        description: 'The name of the workflow, used to ensure concurrency of 1 job per repository'
-        type: string
-        required: true
       deploy_confirmation:
         description: 'Outcome if user manually confirmed the start of the deploy script'
         type: string
         required: true
+      environment:
+        description: 'The environment to build and deploy to'
+        required: true
+        type: string
+        default: 'staging'
       version_bump:
         description: 'Choose version bump granularity'
-        required: true
+        required: false
         type: string
         default: 'minor'
       version_file_path:
@@ -21,44 +22,11 @@ on:
         type: string
         required: false
         default: app/version.php
-      git_target_repository:
-        description: The target repository for the build
-        type: string
-        required: true
-      git_target_repository_folder:
-        description: The folder in which the target repository will be checked out
-        type: string
-        required: false
-        default: target_repository_folder
-      ecr_production_image_name:
-        description: The name the production docker image. This is also the name of the ECR repository (optional)
-        type: string
-      ecr_staging_image_name:
-        description: The name the staging docker image. This is also the name of the ECR repository (optional)
-        type: string
-      ecr_util_image_name:
-        description: The name the util docker image. This is also the name of the ECR repository (optional)
-        type: string
       dockerfile:
         description: Relative dockerfile to the docker file seen from the repository root. No leading slash.
         type: string
-        required: true
-      ecs_service_name:
-        description: 'ECS service name'
-        type: string
         required: false
-      ecs_service_tag:
-        description: 'The tag given to the service, used to find the service name'
-        type: string
-        required: false
-      ecs_cluster:
-        description: 'ECS cluster name'
-        type: string
-        required: true
-      ecs_region:
-        description: 'AWS region'
-        type: string
-        required: true
+        default: 'deployment/dockerfiles/code/Dockerfile'
       programming_language:
         description: 'Choose the programming language of the project'
         required: false
@@ -114,16 +82,22 @@ on:
         description: Composer authentication key
 
 concurrency:
-  group: ${{ inputs.name }}
+  group: ${{ github.repository }}
   cancel-in-progress: false
 
 jobs:
-  print-out-master:
-    name: Print out master branch
+  check-environment:
+    name: Check if proper environment is passed
     runs-on: ubuntu-latest
     steps:
-      - id: print-out-master
-        run: echo "Master branch"
+      - name: Only allow staging and production
+        run: |
+          if [[ "${{ inputs.environment }}" == "staging" || "${{ inputs.environment }}" == "production" ]]; then
+          echo "Running workflow with environment: ${{ inputs.environment }}."
+          else
+          echo "Invalid environment. Only 'staging' or 'production' are allowed."
+          exit 1
+          fi
 
   ensure-master-branch:
     name: Check current branch
@@ -150,7 +124,7 @@ jobs:
           fi
   tag:
     name: Generating new GitHub tag
-    needs: [ensure-master-branch, ensure-app-ci-key]
+    needs: [ensure-master-branch, ensure-app-ci-key, check-environment]
     outputs:
       new_tag: ${{ steps.tag_version.outputs.new_tag }}
     runs-on: ubuntu-latest
@@ -180,6 +154,7 @@ jobs:
           repository: rentmanpublic/actions
           token: ${{ secrets.GITHUB_TOKEN }}
           path: actions
+          ref: feature/multi-region-deploy
       - name: Create Git Auth Token
         if: ${{ inputs.is_repository_protected == true }}
         uses: actions/create-github-app-token@v1
@@ -190,9 +165,10 @@ jobs:
       - name: Checkout to release repo
         uses: actions/checkout@v4
         with:
-          repository: ${{ inputs.git_target_repository }}
+          repository: ${{ github.repository }}
           token: ${{ steps.github-token.outputs.token || secrets.GITHUB_TOKEN }}
-          path: ${{ inputs.git_target_repository_folder }}
+          path: target_repository_folder
+          ref: ${{ github.ref }}
       - name: use node
         if: ${{ inputs.node_version != '' }}
         uses: actions/setup-node@v4
@@ -205,13 +181,13 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ steps.github-token.outputs.token || secrets.GITHUB_TOKEN }}
           GIT_TAG: ${{ needs.tag.outputs.new_tag }}
-          TARGET_REPOSITORY_FOLDER: ${{ inputs.git_target_repository_folder }}
+          TARGET_REPOSITORY_FOLDER: target_repository_folder
           VERSION_FILE_PATH: ${{ inputs.version_file_path }}
-          TARGET_REPOSITORY: ${{ inputs.git_target_repository }}
+          TARGET_REPOSITORY: ${{ github.repository }}
           PROGRAMMING_LANGUAGE: ${{ inputs.programming_language }}
 
-  determine-image-name:
-    name: Determine image name based on environment
+  determine-ecr-image-name:
+    name: Determine ecr image name based on environment
     needs: push-new-tag
     outputs:
       image_name: ${{ steps.image_name.outputs.image_name }}
@@ -223,22 +199,26 @@ jobs:
           repository: rentmanpublic/actions
           token: ${{ secrets.GITHUB_TOKEN }}
           path: actions
+      - name: Checkout to release repo
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ github.repository }}
+          token: ${{ steps.github-token.outputs.token || secrets.GITHUB_TOKEN }}
+          path: target_repository_folder
+          ref: feature/multi-region-deploy
       - name: Check which image name to use based on enviroment
         id: image_name
         run: |
           chmod 700 actions/scripts/determine_image_name.sh
           actions/scripts/determine_image_name.sh
         env:
-          SELECTED_ECS_CLUSTER: ${{ inputs.ecs_cluster }}
-          PRODUCTION_IMAGE_NAME: ${{ inputs.ecr_production_image_name }}
-          STAGING_IMAGE_NAME: ${{ inputs.ecr_staging_image_name }}
-          UTIL_IMAGE_NAME: ${{ inputs.ecr_util_image_name }}
+          ENVIRONMENT: ${{ inputs.environment }}
   docker-build:
     name: Build image
-    needs: [tag, determine-image-name]
+    needs: [tag, determine-ecr-image-name]
     uses: rentmanpublic/actions/.github/workflows/ecr-build-and-push.yml@master
     with:
-      image_name: ${{ needs.determine-image-name.outputs.image_name }}
+      image_name: ${{ needs.determine-ecr-image-name.outputs.image_name }}
       image_tag: latest ${{ needs.tag.outputs.new_tag }}
       version: ${{ needs.tag.outputs.new_tag }}
       dockerfile: ${{ inputs.dockerfile }}
@@ -260,12 +240,9 @@ jobs:
   deploy:
     name: Deploy to ECS
     needs: docker-build
-    uses: rentmanpublic/actions/.github/workflows/ecs-redeploy-service.yml@master
+    uses: rentmanpublic/actions/.github/workflows/ecs-redeploy-service.yml@feature/multi-region-deploy
     with:
-      service_name: ${{ inputs.ecs_service_name }}
-      service_tag: ${{ inputs.ecs_service_tag }}
-      cluster_name: ${{ inputs.ecs_cluster }}
-      region: ${{ inputs.ecs_region }}
+        environment: ${{ inputs.environment }}
     secrets:
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
